### ISSUE TITLE
Execute Sale

### ISSUE THREAD

**Issue by kespinola** [holaplex/metaplex-program-library#13]
### Goal
Complete the sale of an NFT when a listing matches an offer.
Payout spl token to both the buyer and the seller based on multiple of the SOL sale price.
The split of spl token to the buyer and the seller is configured on the reward center listing reward rules

### Requirements
- Mark the purchased_at on the listing and offer using clock current time.
- CPI call to auctioneer_execute_sale
- Listing reward rules tracks seller_reward_payout_basis_points. The rest of the payout goes to the buyer.
- Listing rewards tracks payout_divider which is used to determine the amount of SPL token to payout compared to the lamports. For example, if the payout_divider is 2 and the sale was for 2,000,000,000 lamports the user will get 1,000,000,000 SPL token (or half the amount of the sale)

**Comment by sunguru98** [comment]
Closing this issue in favour of #16
