### ISSUE TITLE
[Feature]: Update Listing and Offers Actions

### ISSUE THREAD

**Issue by kespinola** [holaplex/metaplex-program-library#20]
### Which package is this feature request for?

listing-rewards

### Feature

Active listings and offers can have their price updated.

### Standard Change?

Yes

### Listings
- The listing should already be initialized and not have canceled at or purchased at set.
- The price is updated on the listings.
- The nft associated the listing is owned by the wallet updating the listing.

### Offers
- The offer should already be initialized and not have canceled at or purchased at set.
- When the offer is for more the difference is deducted from the wallet account and transferred to the user's escrow account.
- When the offer is for less than the current offer price the difference is transferred from the user's escrow account and sen't back to their wallet (or ata).

**Comment by sunguru98** [comment]
Closing this in favor of #21
