### ISSUE TITLE
[Feature]: Configurable reward divider or multiplier

### ISSUE THREAD

**Issue by kespinola** [holaplex/metaplex-program-library#33]
### Which package is this feature request for?

reward-center

### Feature

Authorities of the reward center can choose between calculating rewards based on a divider or multiplier based on configuration of reward rules.

### Standard Change?

No

### Ideal solution or implementation

Extend the reward rules to track mathematical operand for calculating payout using an enum.

```rust
enum PayoutOperation {
  Multiple,
  Divide,
}

struct RewardRules {
  mathematical_operand: PayoutOperation,
  payout_numeral: u16
}
```

When calculating the payout first evaluate the mathematical operand and then decide on where to divide or multiply by the payout numeral.

**Comment by sunguru98** [comment]
Closing this on favor of #34
